---

# Python Part 7. Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

## The Basic Numpy ```ndarray```
It is standard to import numpy using the *alias* np. In the code below we import numpy and create a simple ```ndarray``` using the numpy ```array([])``` method. Run this code in the cell below.
```python
import numpy as np

a = np.array([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"The type of a is {type(a)}")
```

---

In [31]:
import numpy as np

a = np.array([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"The type of a is {type(a)}")

a = [1. 2. 3.]
The type of a is <class 'numpy.ndarray'>


---

As shown in the output above, we see that ```a``` is ```<class 'numpy.ndarray'>```. Thus, ```a``` will have attributes and methods which can be found at the official documentation [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). For example numpy ndarrays have ```shape``` and ```dtype``` attributes. Run the following code in the cell below.
```python
a = np.array([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"The shape of a is {a.shape}")
print(f"The types in a are {a.dtype}")

b = np.array([1, 2, 3, 4, 5])
print(f"b = {b}")
print(f"The shape of b is {b.shape}")
print(f"The types in b are {b.dtype}")

```

---

In [4]:
a = np.array([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"The shape of a is {a.shape}")
print(f"The types in a are {a.dtype} \n")

b = np.array([1, 2, 3, 4, 5])
print(f"b = {b}")
print(f"The shape of b is {b.shape}")
print(f"The types in b are {b.dtype}")

a = [1. 2. 3.]
The shape of a is (3,)
The types in a are float64 

b = [1 2 3 4 5]
The shape of b is (5,)
The types in b are int64


---

Numpy ```ndarray``` types also has *fast* methods for computing properties such as:
* ```ndarray.mean()```: Mean of values in ```ndarray```
* ```ndarray.max()```: Maximum of values in ```ndarray```
* ```ndarray.argmax()```: Index of the maximum value in ```ndarray```
* ```ndarray.min()```: Minimum of values in ```ndarray```
* ```ndarray.argmin()```: Index of the minimum value in ```ndarray```

For example run the following code in the cell below.
```python
a = np.array([10.0, 4.0, -3.5, 9.75, 20.1, 7.0])

print(f"a = {a}")
print(f"The mean of values in a: {a.mean()}")
print(f"The maximum of values in a: {a.max()}")
print(f"The argmax of values in a: {a.argmax()}")
print(f"The minimum of values in a: {a.min()}")
print(f"The argmin of values in a: {a.argmin()}")
```

---

In [25]:
a = np.array([10.0, 4.0, -3.5, 9.75, 20.1, 7.0])

print(f"a = {a}")
print(f"The mean of values in a: {a.mean()}")
print(f"The maximum of values in a: {a.max()}")
print(f"The argmax of values in a: {a.argmax()}")
print(f"The minimum of values in a: {a.min()}")
print(f"The argmin of values in a: {a.argmin()}")


a = [10.    4.   -3.5   9.75 20.1   7.  ]
The mean of values in a: 7.891666666666667
The maximum of values in a: 20.1
The argmax of values in a: 4
The minimum of values in a: -3.5
The argmin of values in a: 2


---

## Column and Row Vector Representations in Numpy

The basic numpy ```ndarray``` types shown above can be converted into representations of linear algebraic *column vectors* by explicitly setting the ```shape``` to be $(m, 1)$ where $m$ is the number of elements in the the column vector. For example, run the following code in the cell below.
```python
a = np.array([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"The old shape of a is {a.shape}")

a.shape = (3, 1)
print(f"The new shape of a is {a.shape}")
print(f"a = {a}")
```

---

In [29]:
a = np.array([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"The old shape of a is {a.shape}")

a.shape = (3, 1)
print(f"The new shape of a is {a.shape}")
print(f"a = {a}")


a = [1. 2. 3.]
The old shape of a is (3,)
The new shape of a is (3, 1)
a = [[1.]
 [2.]
 [3.]]


---

The basic numpy ```ndarray``` types can also be converted into representations of linear algebraic *row vectors* by explicitly setting the ```shape``` to be $(1, n)$ where $n$ is the number of elements in the rows of the column vector. For example, run the following code in the cell below.
```python
a = np.array([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"The old shape of a is {a.shape}")

a.shape = (1, 3)
print(f"The new shape of a is {a.shape}")
print(f"a = {a}")
```

---

In [30]:
a = np.array([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"The old shape of a is {a.shape}")

a.shape = (1, 3)
print(f"The new shape of a is {a.shape}")
print(f"a = {a}")

a = [1. 2. 3.]
The old shape of a is (3,)
The new shape of a is (1, 3)
a = [[1. 2. 3.]]


---

## Matrices

Column vectors are special cases of linear algebraic matrices. Matrices can be constructed by passing into the numpy ```array([])``` method a list whose elements are the rows of your desired matrix in a list each. Note that this implies each each row list must have the same number of elements. For example, run the following code in the cell below. 

```python
A = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print(f"The shape of A is {A.shape}")
print(f"A = {A} \n")

print(f"Row 0 = {A[0, :]}")
print(f"Row 1 = {A[1, :]} \n")

print(f"Column 0 = {A[:, 0]}")
print(f"Column 1 = {A[:, 1]} \n")

print(f"Element at row index 0 and column index 2 = {A[0, 2]}")

```


---

In [21]:
A = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print(f"The shape of A is {A.shape}")
print(f"A = {A} \n")

print(f"Row 0 = {A[0, :]}")
print(f"Row 1 = {A[1, :]} \n")

print(f"Column 0 = {A[:, 0]}")
print(f"Column 1 = {A[:, 1]} \n")

print(f"Element at row index 0 and column index 2 = {A[0, 2]}")

The shape of A is (2, 3)
A = [[1. 2. 3.]
 [4. 5. 6.]] 

Row 0 = [1. 2. 3.]
Row 1 = [4. 5. 6.] 

Column 0 = [1. 4.]
Column 1 = [2. 5.] 

Element at row index 0 and column index 2 = 3.0


In [15]:
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
A[0, :]

array([1., 2., 3.])

![](root_image.jpeg)